>>> Loading SCALE Standard Composition Library from /opt/scale6.3.0_data/scale.rev40.sclib
***Created 5 infinite homogeneous cells from unreferenced mixtures.
*** Adjusted number of batches to 36 to be divisible by the number of nodes (36)
Calculating volume batches 1-36 of 36
Tracing 10004569 rays per core along the Z axis
[owl:170874] 35 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[owl:170874] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
>>> Loading CE library /opt/scale6.3.1-mpi/data/ce_v7.1_endf.xml
Loading      nuclide       li-6 @ 900K
Loading      nuclide       li-6 @ 1200K
Broadening   nuclide       li-6 @ 923.15K
Loading      nuclide       li-7 @ 900K
Loading      nuclide       li-7 @ 1200K
Broadening   nuclide       li-7 @ 923.15K
Loading      nuclide       be-9 @ 900K
Loading      nuclide       be-9 @ 1200K
Broadening   nuclide       be-9 @ 923.15K
Loading      nuclide       f-19 @ 900K
Loading      nuclide       f-19 @ 1200K
Broadening   nuclide       f-19 @ 923.15K
Loading      nuclide      u-235 @ 900K
Loading      nuclide      u-235 @ 1200K
Broadening   nuclide      u-235 @ 923.15K
Loading      nuclide      u-238 @ 900K
Loading      nuclide      u-238 @ 1200K
Broadening   nuclide      u-238 @ 923.15K
Reinitializing LFG control, ignoring new seed 2272013 (actual seed 112358) and resetting stream ID
*** Disabling parallel HDF5 calls
::: Building model
>>> Splitting compound 3006000 into at% {3006012: 0.9893, 3006013: 0.0107}
>>> Splitting compound 6000 into at% {6012: 0.9893, 6013: 0.0107}
>>> Creating default boundary mesh from (-215 -215 -30) to (215 215 460) for ORANGE geometry
::: Building physics 'physics_mg_mc'
::: Building tallies
::: Building sources
Building source 'cuboid_fission'
::: Building Shift solver internals
::: Building Shift sources
::: Initializing Shift solver
::: Building Shift tallies
::: Skipping transport due to user option
::: Run complete


***Warning: This problem will not be run because parm=check was entered in the analytical sequence specification.
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5G.c line 893 in H5Gclose(): decrementing group ID failed
    major: Symbol table
    minor: Unable to decrement reference count
  #001: H5Iint.c line 1155 in H5I_dec_app_ref(): can't decrement ID ref count
    major: Object ID
    minor: Unable to decrement reference count
  #002: H5Iint.c line 1107 in H5I__dec_app_ref(): can't decrement ID ref count
    major: Object ID
    minor: Unable to decrement reference count
  #003: H5Iint.c line 1011 in H5I__dec_ref(): can't locate ID
    major: Object ID
    minor: Unable to find ID information (already closed?)
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5G.c line 893 in H5Gclose(): decrementing group ID failed
    major: Symbol table
    minor: Unable to decrement reference count
  #001: H5Iint.c line 1155 in H5I_dec_app_ref(): can't decrement ID ref count
    major: Object ID
    minor: Unable to decrement reference count
  #002: H5Iint.c line 1107 in H5I__dec_app_ref(): can't decrement ID ref count
    major: Object ID
    minor: Unable to decrement reference count
  #003: H5Iint.c line 1011 in H5I__dec_ref(): can't locate ID
    major: Object ID
    minor: Unable to find ID information (already closed?)
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5F.c line 982 in H5Fflush(): unable to synchronously flush file
    major: File accessibility
    minor: Unable to flush data from cache
  #001: H5F.c line 946 in H5F__flush_api_common(): invalid object identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #002: H5VLint.c line 1779 in H5VL_vol_object(): invalid identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5F.c line 982 in H5Fflush(): unable to synchronously flush file
    major: File accessibility
    minor: Unable to flush data from cache
  #001: H5F.c line 946 in H5F__flush_api_common(): invalid object identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #002: H5VLint.c line 1779 in H5VL_vol_object(): invalid identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5T.c line 1911 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5I.c line 550 in H5Iget_ref(): can't get ID ref count
    major: Object ID
    minor: Can't get value
  #001: H5Iint.c line 1361 in H5I_get_ref(): can't locate ID
    major: Object ID
    minor: Unable to find ID information (already closed?)
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5F.c line 1060 in H5Fclose(): decrementing file ID failed
    major: File accessibility
    minor: Unable to close file
  #001: H5Iint.c line 1155 in H5I_dec_app_ref(): can't decrement ID ref count
    major: Object ID
    minor: Unable to decrement reference count
  #002: H5Iint.c line 1107 in H5I__dec_app_ref(): can't decrement ID ref count
    major: Object ID
    minor: Unable to decrement reference count
  #003: H5Iint.c line 1011 in H5I__dec_ref(): can't locate ID
    major: Object ID
    minor: Unable to find ID information (already closed?)
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5I.c line 550 in H5Iget_ref(): can't get ID ref count
    major: Object ID
    minor: Can't get value
  #001: H5Iint.c line 1361 in H5I_get_ref(): can't locate ID
    major: Object ID
    minor: Unable to find ID information (already closed?)
HDF5-DIAG: Error detected in HDF5 (1.14.1-2) thread 0:
  #000: H5F.c line 1060 in H5Fclose(): decrementing file ID failed
    major: File accessibility
    minor: Unable to close file
  #001: H5Iint.c line 1155 in H5I_dec_app_ref(): can't decrement ID ref count
    major: Object ID
    minor: Unable to decrement reference count
  #002: H5Iint.c line 1107 in H5I__dec_app_ref(): can't decrement ID ref count
    major: Object ID
    minor: Unable to decrement reference count
  #003: H5Iint.c line 1011 in H5I__dec_ref(): can't locate ID
    major: Object ID
    minor: Unable to find ID information (already closed?)
